In [1]:
#imports for pytorch
import torch

In [19]:
# matrix operations

x = torch.randn(2,3,3)

print(x.dim())
print(x)

# mean average across all rows:
print(x.mean(dim=0))

# mean average across all columns:
print(x.mean(dim=1))



3
tensor([[[ 1.4821, -1.1986, -1.7681],
         [-0.1040,  1.3528,  0.1455],
         [ 0.8396, -1.2507,  1.1963]],

        [[-0.7690,  1.3644, -2.2724],
         [-0.3137, -0.0900,  1.8761],
         [ 0.8913,  0.0039, -0.8431]]])
tensor([[ 0.3565,  0.0829, -2.0203],
        [-0.2089,  0.6314,  1.0108],
        [ 0.8655, -0.6234,  0.1766]])
tensor([[ 0.7392, -0.3655, -0.1421],
        [-0.0638,  0.4261, -0.4131]])


In [ ]:
from core.models.models import get_model

model = get_model("simplenn")

x = torch.randn(1, 784)
print(x.shape)
print(x)

torch.Size([1, 784])
tensor([[ 1.3010e+00, -1.0689e-01, -7.4989e-01, -2.0869e+00, -1.3737e+00,
         -3.5905e-01, -2.4881e-01,  9.1363e-01,  7.1100e-02, -9.5133e-01,
         -7.3388e-01, -4.8723e-01, -9.7370e-02,  4.8987e-01,  4.9584e-01,
         -2.5114e-01, -8.7872e-01, -7.4041e-01,  7.5520e-01,  4.0964e-02,
          5.4935e-01,  5.9995e-01,  1.6080e+00, -5.3486e-01,  8.3336e-01,
         -7.8173e-01,  3.8639e-01, -5.4866e-01,  8.4736e-01, -7.0127e-01,
          1.4573e+00, -2.2512e-01, -3.9561e-02,  2.5657e-01,  2.8475e+00,
          9.3503e-01,  4.7500e-01,  5.8211e-01,  5.0122e-01,  3.8139e-01,
          1.7573e-01, -4.9463e-01, -5.5607e-01,  3.3903e-01,  2.4713e-01,
          9.0511e-01, -5.6444e-02,  3.6723e-01, -1.4762e+00, -7.9697e-01,
         -9.7169e-02, -6.9618e-01, -3.4474e-01, -2.2105e-01,  3.0405e-01,
         -2.2189e+00,  1.2084e-01,  3.4104e-01, -7.0530e-01,  1.1234e+00,
         -6.8471e-01,  1.9755e+00,  9.3780e-01, -1.0209e-01, -7.4054e-02,
          1.1521e